import uuid

class BehaviorHandler:
    
    def __init__(self) -> None:
        pass

    def handle(self, definition, entity_data):
        for attribute in definition["attributes"]:
            behavior = attribute.get("behavior")
            
            # If the behavior is AutoGenerated and the attribute is not in the entity data, generate a UUID
            if behavior == "AutoGenerated" and attribute["attributeName"] not in entity_data:
                entity_data[attribute["attributeName"]] = str(uuid.uuid4())
                
        return entity_data